-- Bulk user import for HonorVet Academy
-- Run in Supabase SQL Editor
-- Default password for all users: HonorVet@2024!
-- Users can reset via "Forgot Password" on the login page

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TEMP TABLE tmp_import_users (name text, email text, role text, department text);

INSERT INTO tmp_import_users (name, email, role, department) VALUES
('Aayush Jagga','aayush.jagga@honorvet.com','employee',''),
('Abhinav Sharma','abhinav.sharma@honorvet.com','employee','Healthcare'),
('Adam Smith','adam.smith@honorvettech.com','employee','Healthcare'),
('Adina Anderson','adina.anderson@honorvettech.com','employee','Healthcare'),
('Adina Sanders','adina.sanders@honorvettech.com','employee',''),
('Aditee Singh','aditee.singh@honorvet.com','employee','Healthcare'),
('Ajay Lamba','ajay.lamba@honorvet.com','employee','Healthcare'),
('Ajay Thakur','ajay.thakur@honorvet.com','manager','Information Technology'),
('Aksham Kumar','aksham.kumar@honorvet.com','employee','Information Technology'),
('Alan Pham','alan@alive5.com','employee',''),
('Albert Keller','albert.keller@honorvettech.com','manager','Healthcare'),
('Alex Ross','alex.ross@honorvettech.com','manager','Healthcare'),
('Alton Sadler','alton.sadler@honorvettech.com','employee','Healthcare'),
('Amit Bisht','amit.bisht@honorvet.com','manager',''),
('Amit Kumar','amit.kumar@honorvettech.com','manager',''),
('Andy Allen','andy.allen@honorvettech.com','employee','Healthcare'),
('Ankit Gupta','ankit.gupta@honorvet.com','employee','Healthcare'),
('Apoorva Rajput','apoorva.rajput@honorvet.com','hr','Healthcare'),
('Archie Rich','archie.rich@honorvettech.com','employee','Healthcare'),
('Arthur Swift','arthur.swift@honorvettech.com','manager','Healthcare'),
('Asheesh Mahajan','asheesh.mahajan@honorvettech.com','manager','Healthcare'),
('Ashi Mittal','ashi.mittal@honorvet.com','employee','Information Technology'),
('Atul Chandel','atul.chandel@honorvet.com','manager','Healthcare'),
('Bhea Bolay','bhea.bolay@honorvet.com','employee',''),
('Cammie Gale','cammie.gale@honorvettech.com','employee',''),
('Carlo DePinto','carlo.depinto@honorvettech.com','manager',''),
('Conor A','conor.a@honorvet.com','employee','Healthcare'),
('Davian Snow','davian.snow@honorvettech.com','employee','Healthcare'),
('David M','david.m@honorvet.com','employee','Healthcare'),
('Deepak Sharma','deepak.sharma@honorvet.com','employee','Healthcare'),
('Denise Grace','denise.grace@honorvet.com','employee','Healthcare'),
('Dennis Ratzker','dennis.ratzker@honorvettech.com','manager','Healthcare'),
('Dhananjai Singh','dhananjai.singh@honorvet.com','manager',''),
('Eddy Bruce','eddy.bruce@honorvettech.com','employee','Non-IT'),
('Eric William','eric.william@honorvet.com','employee','Healthcare'),
('Garry Richard','garry.richard@honorvettech.com','hr','Payroll'),
('Gautam Verma','gautam.verma@honorvet.com','manager','Healthcare'),
('Gemma Saylor','gemma.saylor@honorvettech.com','employee','Healthcare'),
('Genny Parks','genny.parks@honorvettech.com','employee','Pharmaceutical'),
('Gunjan Sharma','gunjan.sharma@honorvet.com','employee','Healthcare'),
('Gur Knox','gur.knox@honorvet.com','hr','Payroll'),
('Hannah Kay','hannah.kay@honorvettech.com','manager','Business Development'),
('Harshita Kukreja','harshita.kukreja@honorvet.com','manager','Healthcare'),
('Harshita Sachdeva','harshita.sachdeva@honorvet.com','employee','Healthcare'),
('Heather Brown','heather.brown@honorvettech.com','manager','Healthcare'),
('Himadri Maity','himadri.maity@honorvet.com','employee','Healthcare'),
('Hiral Chauhan','hiral.chauhan@honorvet.com','employee','Healthcare'),
('Jasleen Kaur','jasleen.kaur@honorvet.com','employee','Healthcare'),
('Jasmine Bulawin','jasmine.bulawin@honorvettech.com','hr','Onboarding'),
('Jennifer Louis','jennifer.louis@honorvettech.com','employee','Healthcare'),
('Kacy Ross','kacy.ross@honorvettech.com','manager','Pharmaceutical'),
('Kamran Khan','kamran.khan@honorvet.com','employee','Healthcare'),
('Karan Sharma','karan.sharma@honorvet.com','manager',''),
('Khushi Thapar','khushi.thapar@honorvet.com','employee','Information Technology'),
('Kulbir Kumar','kulbir.kumar@honorvet.com','employee','Healthcare'),
('Mack Ray','mack.ray@honorvettech.com','employee','Healthcare'),
('Manisha Singh','manisha.singh@honorvet.com','hr','Onboarding'),
('Mannu Mor','mannu.mor@honorvet.com','employee','Healthcare'),
('Marites Dela Cruz','marites.delacruz@honorvettech.com','manager','Healthcare'),
('Mark Addison','mark.addison@honorvet.com','manager','Business Development'),
('Mark Austin','mark.austin@honorvettech.com','employee','Pharmaceutical'),
('Melanie Chaudoir','melanie.chaudoir@honorvettech.com','hr','Onboarding'),
('Michael Gulevski','michael.gulevski@honorvet.com','employee','Healthcare'),
('Michael Williams','michael.williams@honorvet.com','manager','Business Development'),
('Miles Basson','miles.basson@honorvettech.com','employee','Information Technology'),
('Monali Sharma','monali.sharma@honorvet.com','employee','Information Technology'),
('Munish Gupta','munish.gupta@honorvet.com','manager','Healthcare'),
('Namita Saylor','namita.saylor@honorvettech.com','employee','Healthcare'),
('Nandini Verma','nandini.verma@honorvet.com','manager','Healthcare'),
('Navneet Kaur','navneet.kaur@honorvet.com','employee','Information Technology'),
('Nia Vinson','nia.vinson@honorvettech.com','employee','Healthcare'),
('Nidhi Chugh','nidhi.chugh@honorvettech.com','manager',''),
('Nikita Bhatti','nikita.bhatti@honorvet.com','employee','Healthcare'),
('Nimi Singh','nimi.singh@honorvet.com','employee','Healthcare'),
('Nimrit Singh','nimrit.singh@honorvet.com','employee','Healthcare'),
('Nitish Sharma','nitish.sharma@honorvet.com','manager','Healthcare'),
('Oshin Sherman','oshin.sherman@honorvettech.com','manager','Non-IT'),
('Paige Taylor','paige.taylor@honorvettech.com','hr','Healthcare'),
('Paula Scott','paula.scott@honorvettech.com','employee','Information Technology'),
('Peter Madison','peter.madison@honorvettech.com','employee','Healthcare'),
('Polly Kay','polly.kay@honorvettech.com','manager','Pharmaceutical'),
('Prisha Smith','prisha.smith@honorvettech.com','employee','Healthcare'),
('Rachelyn Nathan','rachelyn.nathan@honorvettech.com','trainer',''),
('Rajeev Sharma','rajeev.sharma@honorvettech.com','manager','Healthcare'),
('Ravi Bhambri','ravi.bhambri@honorvettech.com','manager','Healthcare'),
('Rex Scott','rex.scott@honorvettech.com','employee','Healthcare'),
('Rhythm Grace','rhythm.grace@honorvettech.com','manager','Healthcare'),
('Richard Kay','richard.kay@honorvettech.com','employee','Non-IT'),
('Rishabh Mohan','rishabh.mohan@honorvet.com','manager',''),
('Robby Kohler','robby.kohler@honorvettech.com','employee','Healthcare'),
('Robyn Smith','robyn.smith@honorvettech.com','manager','Information Technology'),
('Rogers Kay','rogers.kay@honorvettech.com','manager','Healthcare'),
('Rony Kytes','rony.kytes@honorvettech.com','hr','Onboarding'),
('Sage Parker','sage.parker@honorvettech.com','manager','Information Technology'),
('Saira Philips','saira.philips@honorvettech.com','employee','Non-IT'),
('Sakshi Sharma','sakshi.sharma@honorvet.com','employee','Healthcare'),
('Salena Alder','salena.alder@honorvettech.com','employee','Healthcare'),
('Sam Rekhi','sam.r@honorvettech.com','manager','Business Development'),
('Sam Snyder','sam.snyder@honorvettech.com','manager',''),
('Samantha Parks','samantha.parks@honorvettech.com','employee','Healthcare'),
('Samira Ray','samira.ray@honorvettech.com','employee','Healthcare'),
('Sandy Parks','sandy.parks@honorvettech.com','employee','Healthcare'),
('Santos Gibbins','santos.gibbins@honorvettech.com','employee',''),
('Sapna Goswami','sapna.goswami@honorvet.com','employee','Healthcare'),
('Sapna Sharma','sapna.sharma@honorvet.com','employee','Healthcare'),
('Sarah Baker','sarah.baker@honorvettech.com','employee','Healthcare'),
('Sean Carter','sean.carter@honorvettech.com','employee','Healthcare'),
('Shailesh Singh','shailesh.singh@honorvet.com','manager','Healthcare'),
('Shana Taylor','shana.taylor@honorvettech.com','manager','Pharmaceutical'),
('Shelley Daniel','shelley.daniel@honorvettech.com','employee','Healthcare'),
('Shikha Rana','shikha.rana@honorvettech.com','employee','Healthcare'),
('Shivam Mahajan','shivam.mahajan@honorvet.com','employee','Healthcare'),
('Shivangi Pathania','shivangi.pathania@honorvettech.com','employee','Healthcare'),
('Shivansh Sanmotra','shivansh.sanmotra@honorvet.com','manager','Healthcare'),
('Shubham Abrol','shubham.abrol@honorvettech.com','manager','Healthcare'),
('Shubham Bisht','shubham.bisht@honorvet.com','manager','Business Development'),
('Simran Kohler','simran.kohler@honorvettech.com','employee','Healthcare'),
('Stacy Abrol','stacy.abrol@honorvettech.com','employee','Healthcare'),
('Steve Smith','steve.smith@honorvettech.com','trainer','Healthcare'),
('Sumer Kent','sumer.kent@honorvet.com','employee','Information Technology'),
('Sunita Chauhan','sunita.chauhan@honorvettech.com','manager','Healthcare'),
('Suraj Kumar','suraj.kumar@honorvet.com','employee','Information Technology'),
('Surbhi Bhardwaj','surbhi.bhardwaj@honorvet.com','manager','Business Development'),
('Talha Zuberi','talha.zuberi@honorvettech.com','employee','Healthcare'),
('Tanya Awasthi','tanya.awasthi@honorvet.com','admin','Healthcare'),
('Thefanie Balon','thefanie.balon@honorvettech.com','hr','Payroll'),
('Tulsi Arya','tulsi.arya@honorvet.com','manager','Business Development'),
('Tushar Choudhary','tushar.choudhary@honorvet.com','employee',''),
('Urvashi Mahajan','urvashi.mahajan@honorvet.com','employee','Healthcare'),
('Vaidik Tiwari','vaidik.tiwari@honorvet.com','employee','Healthcare'),
('Victor Stone','victor.stone@honorvet.com','hr','Payroll'),
('Vin Smith','vin.smith@honorvettech.com','manager','Non-IT'),
('Vivek Kumar','vivek.kumar@honorvet.com','employee','Healthcare');

-- Step 1: Create auth accounts (bypasses API rate limits)
INSERT INTO auth.users (
  id, instance_id, aud, role, email, encrypted_password,
  email_confirmed_at, raw_user_meta_data, raw_app_meta_data,
  created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change
)
SELECT
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  lower(email),
  crypt('HonorVet@2024!', gen_salt('bf')),
  now(),
  jsonb_build_object('name', name, 'role', role, 'department', department),
  '{"provider":"email","providers":["email"]}'::jsonb,
  now(),
  now(),
  '', '', '', ''
FROM tmp_import_users
ON CONFLICT (email) DO NOTHING;

-- Step 2: Create user profiles linked to auth accounts
INSERT INTO public.users (id, email, name, role, department, created_at)
SELECT
  au.id,
  tu.email,
  tu.name,
  tu.role,
  tu.department,
  now()
FROM auth.users au
JOIN tmp_import_users tu ON au.email = lower(tu.email)
ON CONFLICT (email) DO UPDATE SET
  name       = EXCLUDED.name,
  role       = EXCLUDED.role,
  department = EXCLUDED.department;

-- Cleanup
DROP TABLE tmp_import_users;
